apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-classnalytic-app
  namespace: classnalytic
spec:
  secretName: cert-classnalytic-app
  dnsNames:
  - classnalytic.app
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - classnalytic.app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer